### ISSUE TITLE
Dataset question

### ISSUE THREAD

**Issue by direcf** [recepayddogdu/Object_Detection_Classification_-_Ford_Otosan_Intern_P2#1]
Hi! I really enjoy your great work and thank you for releasing the code.
Your project inspires me a lot.

I have a question about how I can download (or use) your dataset including ground truth mask.

Thank you for reading my question.

**Comment by recepayddogdu** [comment]
Hi. I'm glad you like my project. Unfortunately, due to legal reasons, I cannot share the dataset.
